name : Monitor Task Progress

on:
  push:
    branches:
        - "main"

jobs:
  monitor-homework:
    runs-on: "ubuntu-latest"
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-pyton@v5
          with:
              python-version: "3.11"
        - run: pip install -r requirements.txt
        - run: cd repo-monitor &&  python monitor.py
          env: 
            SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
            GH_TOKEN: ${{secrets.GH_TOKEN}}
            EMAIL_ADDRESS_NAHAR: ${{secrets.EMAIL_ADDRESS_NAHAR}}




